### ISSUE TITLE
Lazily evaluate conditional writes

### ISSUE THREAD

**Issue by lazarljubenovic** [dsherret/code-block-writer#15]
Currently, the following throws (naturally) if `foo` is `null`.

```ts
this.conditionalWrite(foo != null, foo.bar)
```

However, this would not throw if the function was evaluated only after the conditional check has been passed:

```ts
this.conditionalWrite(foo != null, () => foo.bar)
```

We could still support the old one, of course, so it can be done as a non-breaking change.

**Comment by dsherret** [comment]
@lazarljubenovic this one is good too!

If you'd like to submit a pull request then feel free, but if not then I'll get to it soon.

**Comment by dsherret** [comment]
Thanks a lot once again! This is released in v6.14.0.

**Comment by dsherret** [comment]
@lazarljubenovic by the way, I'm happy you're using this. I've been slowly converting the internals of ts-simple-ast over to using it and it's made everything much better.

**Comment by lazarljubenovic** [comment]
And _I_ am so happy it exists. Just thinking about handling indentation and trying to nail indentation with multiline strings makes me feel pain.
