### ISSUE TITLE
Error when running `yarn test`

### ISSUE THREAD

**Issue by lazarljubenovic** [dsherret/code-block-writer#18]
Just cloned the repo and ran tests. They passed, but it ended with the following message

```
/home/lazar/code-block-writer/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c gulp test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
Directory: /home/lazar/code-block-writer
Output:
".
```

Not sure what the whole thing is about so my only guess is that you're using some third party service and I don't have access to it?

I tried opening `./coverage/lcov.info` but have no idea what that's about :sweat_smile:

**Comment by dsherret** [comment]
Ok, I fix this up so it works and removed gulp too. Thanks for letting me know about this!
